### ISSUE TITLE
Unused argument in query error

### ISSUE THREAD

**Issue by jobreu** [chainsawriot/einfach#1]
Thx for creating this really cool package! I will be giving a workshop on combining data from Twitter with survey data tomorrow and will definitely mention it as a great new option for collecting Twitter data via the Academic Track v2 API with a tool that has a GUI and is, hence, very beginner-friendly.

When I tried the package today, I ran the example query and received the following error message:
`Warning: Error in build_query: unused argument (n = 450)`

**Comment by chainsawriot** [comment]
@jobreu Thanks for your interest. Also, thanks for mentioning this package in your workshop.

The reason for the error is that the argument `n` of the function `academictwitteR::get_all_tweets` is pretty new and it's not available in the CRAN version.

I will reflect this in the DESCRIPTION, so that it will install the Github version instead.

Thanks for reporting.

**Comment by jobreu** [comment]
You're welcome! Thx for the quick reply! I also just noticed that myself and can confirm that installing the development version of `academictwitteR` solves the issue.

Two other minor things which I just noticed (for which I don't think opening a PR is warranted):
1. There seems to be an empty argument (two commas) in line 11 of  `einfach_shiny.R` (between `end_tweets` and `data_path`).
2. The line on the Code of Conduct in the ReadMe mentions the name of another package of yours, `oolong` (which is pretty great, too, btw) instead of  `einfach`.
